spring:
  application:
    name: fpis-dev
  profiles:
    active: dev

  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    driver-class-name: com.tmax.tibero.jdbc.TbDriver
    url: jdbc:tibero:thin:@localhost:8629:tibero
    username: tibero1
    password: tibero1
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# MyBatis 설정
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  type-aliases-package: egovframework.example.**.vo
  mapper-locations: classpath:/egovframework/sqlmap/example/mappers/*.xml
  config-location: classpath:/egovframework/sqlmap/example/sql-mapper-config.xml

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: INFO
    com.example: DEBUG
    egovframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
    org.mybatis: DEBUG

